* Mcpdf

Mcpdf is a drop-in replacement for [[http://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/][PDFtk]].

It fixes PDFtk's unicode issues when filling in PDF forms,
and is essentially a command line interface
to the [[http://itextpdf.com/product/itext][iText PDF library]]
with a PDFtk compatible syntax.

** Getting Started

1. Make sure you have installed a
   Java Runtime Environment such as [[http://openjdk.java.net/][OpenJDK]].

2. Download the latest standalone version
   of Mcpdf (jar-with-dependencies).

3. For the sake of brevity,
   we'll refer to this file as =mcpdf.jar=.
   So you should either rename the file
   or create a symlink:

   #+BEGIN_SRC sh
   ln -s mcpdf-X.Y.Z-jar-with-dependencies.jar mcpdf.jar
   #+END_SRC

4. Test it via:

   #+BEGIN_SRC sh
   java -jar mcpdf.jar
   #+END_SRC

** Usage

Mcpdf is a drop-in replacement for PDFtk.
Take a working [[http://www.pdflabs.com/docs/pdftk-man-page/][PDFtk command]]
and replace =pdftk= with =java -jar mcpdf.jar=.
That's all there is to it.

For example, the following command
fills in form data from =DATA.xfdf= into =FORM.pdf=
and writes the result to =RESULT.pdf=.
It also flattens the document to prevent further editing:

#+BEGIN_SRC sh
java -jar mcpdf.jar FORM.pdf fill_form - output - flatten < DATA.xfdf > RESULT.pdf
#+END_SRC

This corresponds exactly to the following PDFtk command:

#+BEGIN_SRC sh
pdftk FORM.pdf fill_form - output - flatten < DATA.xfdf > RESULT.pdf
#+END_SRC

Note that not all PDFtk operations
are implemented at the moment.

[[https://github.com/m-click/mcpdf/issues][Please create an issue tracker entry]]
if you see something missing.

** Advanced Topics

*** Combine with Another Library Version

1. Download the plain JAR file
   (mcpdf-X.Y.Z.jar)
   instead of the jar-with-dependencies.

2. Download the version of the iText PDF library
   you want to use (textpdf-X.Y.Z.jar).

3. Run both in combination:

   #+BEGIN_SRC sh
   java -cp itextpdf-X.Y.Z.jar:mcpdf-X.Y.Z.jar aero.m_click.mcpdf.Main
   #+END_SRC

*** Build from Source

1. Make sure you have installed [[https://maven.apache.org/][Maven]] and [[http://git-scm.com/][Git]].

2. Download the latest Mcpdf source
   and change into that folder:

   #+BEGIN_SRC sh
   git clone https://github.com/m-click/mcpdf.git
   cd mcpdf
   #+END_SRC

3. Build the plain JAR file
   as well as the jar-with-dependencies:

   #+BEGIN_SRC sh
   mvn package
   #+END_SRC

   This will download
   the correct version of the iText PDF library
   and all required Maven modules automatically.

4. You'll find the JAR files in the =target= subfolder.

*** Deploy Releases

Mcpdf uses the [[https://docs.sonatype.org/display/Repository/Sonatype%2BOSS%2BMaven%2BRepository%2BUsage%2BGuide][Sonatype OSSRH]]
(OSS Repository Hosting Service).
The project creation ticket was [[https://issues.sonatype.org/browse/OSSRH-8759][OSSRH-8759]].

1. Create =~/.m2/settings.xml=:

   #+BEGIN_SRC xml
   <settings>
     <servers>
       <server>
         <id>sonatype-nexus-snapshots</id>
         <username>...</username>
         <password>...</password>
       </server>
       <server>
         <id>sonatype-nexus-staging</id>
         <username>...</username>
         <password>...</password>
       </server>
     </servers>
   </settings>
   #+END_SRC

2. Create a new release
   and upload it to the OSSRH staging area:

   #+BEGIN_SRC sh
   mvn release:clean
   mvn release:prepare
   mvn release:perform
   #+END_SRC

3. [[https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide#SonatypeOSSMavenRepositoryUsageGuide-8a.ReleaseIt][Follow the release instructions]].

4. When everything was fine, push to GitHub:

   #+BEGIN_SRC sh
   git push
   #+END_SRC
